// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
namespace GeometryFriendsAgents
{
	public class CircleEdge
	{
		private CircleNode _parent;
		private CircleNode _child;
		private int _action; // Specific to each edge, this represents the action that takes the agent from one state to the other (State AKA node)
		private bool _busy;

		public CircleEdge (CircleNode p, CircleNode c, int a)
		{
			this._parent = p;
			this._child = c;
			this._action = a;
			this._busy = false;
		}

		public void setBusy()
		{
			this._busy = true;
		}

		public void setNotBusy()
		{
			this._busy = false;
		}

		public bool isBusy()
		{
			return this._busy;
		}

		public CircleNode getParent()
		{
			return this._parent;
		}

		public CircleNode getChild()
		{
			return this._child;
		}

		public int getAction()
		{
			return this._action;
		}

	}
}

