// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace GeometryFriendsAgents
{
	public class CircleActions : Actions
	{
		private static Random rndAction;

		public CircleActions () : base(4)
		{
			rndAction = new Random();
		}

		public override int getRandomAction ()
		{
			return rndAction.Next(this.getNrActions());
		}
	}
}

