// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections;

namespace GeometryFriendsAgents
{
	public class CircleNode
	{
		private ArrayList _edges;
        public bool [] _busyActions;
		private CircleNode _parent;
		private State _state;

		public CircleNode ()
		{
			this._edges = new ArrayList();
			this._parent = null;
			this._state = null;
            this._busyActions = new bool[5];
            _busyActions[0] = false;
            _busyActions[1] = false;
            _busyActions[2] = false;
			_busyActions[3] = false;
            _busyActions[4] = true;
		}

		public CircleNode(State s)
		{
			this._edges = new ArrayList();
			this._parent = null;
            this._state = s;
            this._busyActions = new bool[5];
            _busyActions[0] = false;
            _busyActions[1] = false;
            _busyActions[2] = false;
			_busyActions[3] = false;
            _busyActions[4] = true;
		}

        public void setActionBusy(int action)
        {
            _busyActions[action] = true;
        }

        public bool isActionBusy(int action)
        {
            return (bool) _busyActions[action];
        }

		public State getState()
		{
			return this._state;
		}

		public bool allActionsBusy()
		{
			foreach(bool b in _busyActions)
			{
				if(!b)
					return false;
			}
			return true;
		}

		public bool isBusy()
		{
            if (this.allActionsBusy())
            {
                if (_edges.Count == 0)
                    return true;
            }
            return false;
		}

		public int getNrNodes()
		{
			return this._edges.Count;
		}

		public CircleNode getParent()
		{

			return this._parent;
		}

		public void setParent(CircleNode p)
		{
			this._parent = p;
		}

		public void addEdge(CircleNode child, int action)
		{
			CircleEdge newEdge = new CircleEdge(this, child, action);
            newEdge.setBusy();
			this._edges.Add(newEdge);
			child.setParent(this);
		}

		public void removeEdge(CircleNode child)
		{
			foreach(CircleEdge i in this._edges)
			{
				if( i.getChild().Equals(child) )
				{
					this._edges.Remove(i);
					return;
				}
			}
		}

		public bool isConnected(CircleNode n)
		{
			foreach(CircleEdge i in this._edges)
			{
				if( i.getChild().Equals(n) )	// Might need implementation of Equals in order to guarantee functionality
					return true;
			}
			return false;
		}
	}
}

