// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections;


namespace GeometryFriendsAgents
{
	public class Path
	{
		public ArrayList _path;
		public Path ()
		{
			_path = new ArrayList();
		}
		public ArrayList path
		{
			get { return _path; }
			set { _path = value; }
		}

		public void AddNewPoint(float x, float y)
		{
			Point p = new Point(x, y);
			path.Add(p);
		}

        public void AddNewPoint(Point p)
        {
            path.Add(p);
        }

	}
}

