// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
namespace GeometryFriendsAgents
{
	public class Point
	{
		private float _x;
		private float _y;						// replace for the platform that signalizes where we are | keep y | doesnt even mather
		private bool _toPlatform;		// for the cicle this means jumping to a higher platform, for the rectangle it means tilting
		private bool _gap;				// crossover to next platform, typically this implies the platforms are on the same y-axis
		private bool _turningPoint;		// speed inversion, this means that near to the end of the next (maybe current?) point we want to be slowed down 
        private bool _gapStart;
        private bool _fall;
        private bool _fallGap;
		private bool _diamondAbove;
        private bool _morph;
        private bool _tilt;
        private int _size;
        private Obstacles.Obstacle _platform;
        public int numberOfCollectibles;
        private int distanceMomentum;
        private int distancePlatform;
        
		public Point (float x, float y)
		{
			this._x = x;
            this._y = y;
			TurningPoint = false;
			Gap = false;
			ToPlatform = false;
            Fall = false;
            StartGap = false;
			DiamondAbove = false;
            Tilt = false;
            Morph = false;
            FallGap = false;
            numberOfCollectibles = 0;
		}

		public bool DiamondAbove
		{
			get { return _diamondAbove; }
			set { _diamondAbove = value; }
		}

        public bool StartGap
        {
            get { return _gapStart; }
            set { _gapStart = value; }
        }

        public bool Fall
        {
            get { return _fall; }
            set { _fall = value; }
        }

        public bool FallGap
        {
            get { return _fallGap; }
            set { _fallGap = value; }
        }

        public float x
        {
            get { return _x; }
            set { _x = value; }
        }
        
		public float y
		{
			get { return _y; }
			set { _y = value; }
		}

		public bool TurningPoint
		{
			get { return _turningPoint; }
			set { _turningPoint = value; }
		}

		public bool Gap
		{
			get { return _gap; }
			set { _gap = value; }
		}

		public bool ToPlatform
		{
			get { return _toPlatform; }
			set { _toPlatform = value; }
		}

        public bool Tilt
        {
            get { return _tilt; }
            set { _tilt = value; }
        }

        public bool Morph
        {
            get { return _morph; }
            set { _morph = value; }
        }

        public int Size
        {
            get { return _size; }
            set { _size = value; }
        }

        public Obstacles.Obstacle Platform
        {
            get { return _platform; }
            set { _platform = value; }
        }

        public int DistancePlatform
        {
            get { return distancePlatform; }
            set { distancePlatform = value; }
        }

        public int DistanceMomentum
        {
            get { return distanceMomentum; }
            set { distanceMomentum = value; }
        }
        
        public bool flagsTrue()
        {
            return ToPlatform || Gap || TurningPoint || StartGap || Fall || DiamondAbove || Tilt || Morph || FallGap;
        }

	}
}

